import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-recommend-navigation',
  templateUrl: './recommend-navigation.component.html',
  styleUrls: ['./recommend-navigation.component.scss']
})
export class RecommendNavigationComponent implements OnInit {

  data=[
    
    {
      title:'小鱼笔记资源',
      data:[
        {
          name:'一个sp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个sp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个sp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个sp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个tp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个yy',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个web',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
      ]
    },
    {
      title:'小鱼笔记资源',
      data:[
        {
          name:'一个sp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个tp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个yy',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个web',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
      ]
    },
    {
      title:'小鱼笔记资源',
      data:[
        {
          name:'一个sp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个tp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
  
      ]
    },
    {
      title:'小鱼笔记资源',
      data:[
        {
          name:'一个sp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个tp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个sp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个sp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个yy',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个web',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
      ]
    },
    {
      title:'小鱼笔记资源',
      data:[
        {
          name:'一个sp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
       
        {
          name:'一个yy',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个web',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
      ]
    },
    {
      title:'小鱼笔记资源',
      data:[
        {
          name:'一个sp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个tp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个yy',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个web',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
      ]
    },
    {
      title:'小鱼笔记资源',
      data:[
        {
          name:'一个sp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个tp',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个yy',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
        {
          name:'一个web',
          desc:'一个很有趣的笔记',
          url:'https://www.google.cn/s2/favicons?domain=www.digitalartsonline.co.uk'
        },
      ]
    },
    
  ]
  constructor() { }

  ngOnInit() {
  }

}
